version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'todo-db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'
  web:
    image: shutovna/todo
    ports:
      - 8080:8080